/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mamunozg' at '1/18/18 4:36 PM' with Gradle 2.6
 *
 * @author mamunozg, @date 1/18/18 4:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
