/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mamunozg' at '11/21/17 4:43 PM' with Gradle 2.1
 *
 * @author mamunozg, @date 11/21/17 4:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
